### PR TITLE
Add plotly

### PR DESCRIPTION
**Pull request by jtpio**
## References

Trying the latest `plotly` which should now bundle the prebuilt lab extension: 

https://github.com/plotly/plotly.py/issues/3055#issuecomment-853125453

## Code changes

Update the demo site.

## User-facing changes

Users of the demo site can create basic Plotly figures:

https://user-images.githubusercontent.com/591645/121752681-f0838b00-cb10-11eb-80f2-25ee8dca026c.mp4

### CODE REVIEW

**Comment by bollwyvl** [comment]
We could move lint out into a separate job so it doesn't block getting insights...

**Comment by bollwyvl** [comment]
:cry: `index.es6.js:283 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.`

Do they have a mimerenderer?

**Comment by jtpio** [comment]
> Do they have a mimerenderer?

Should be fixed by https://github.com/jtpio/jupyterlite/pull/129/commits/fa93aa24d3693d8e48c95a21c263f7f0150e6544

**Comment by jtpio** [comment]
Some progress (locally):

image

**Comment by jtpio** [comment]
Hitting: https://github.com/plotly/plotly.py/blob/34d61d0a7d4753cfc1646092aa4af86b1c1960b7/packages/python/plotly/plotly/io/_renderers.py#L391-L394

image

So now might be a good time to start having a minimal `IPython` (mostly `IPython.display`) that would run in jupyterlite.

**Comment by bollwyvl** [comment]
> start having a minimal `IPython`

Yerp. `pyolite` (or daugher-of- #116) can ship one to `site-packages`, but not with `flit`... :crying_cat_face: 

Indeed... actually _being_ a distribution, and not just a `py_module` named `IPython`, just never-to-be-deployed-to-pypi (except inside a `federated_extension`-containing package) is probably going to be needed. Will bring up over there...

**Comment by jtpio** [comment]
At least the base figure can be displayed when omitting the `fig.show():

image

Maybe we can have a small patch specific to Plotly for now, similar to the one for `matplotlib`:

https://github.com/jtpio/jupyterlite/blob/7b81d32e5667647124f8e1b2e6c8009fc54942bb/packages/pyolite-kernel/py/pyolite/pyolite/patches.py#L11

**Comment by jtpio** [comment]
Should be good enough now for the first iteration:

https://user-images.githubusercontent.com/591645/121752681-f0838b00-cb10-11eb-80f2-25ee8dca026c.mp4

**Pull request merged**
