### PR TITLE
add wordmark

### PR DESCRIPTION
**Pull request by bollwyvl**
> of course open to **any** feedback!

Screenshot from 2021-05-15 16-17-31

## References

- continues #86

## Code changes

- the `wordmark.svg` and `logo.svg` both contain some more content in inkscape layers

## User-facing changes

- in the docs, there would be a word mark

## Backwards-incompatible changes

- n/a

## Alternatives

> these are stored within `wordmark.svg`, which is probably not permanent.

### CODE REVIEW

**Comment by jtpio** [comment]
Looks great, thanks!

Maybe we can go for the orange version first, and then check whether we would like to switch to another one? The yellow / black one also looks good.

Should we add it to the README as well? This could even replace the "JupyterLite" title and be placed above the badges.

**Comment by bollwyvl** [comment]
>  go for the orange version first

Sounds good. I'll split out/optimize just ol' orange, and leave the working stuff in another file.

> Should we add it to the README as well?

Ehm, I reckon we should wait until it actually points at something on `main`.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by bollwyvl** [comment]
Oh, whoops, didn't optimize that... it's ok, we can do more with it in post.

**Pull request merged**
