### PR TITLE
Add ipympl example

### PR DESCRIPTION
**Pull request by martinRenou**
https://user-images.githubusercontent.com/591645/124771250-4514fd00-df3b-11eb-834b-96d32aec99a7.mp4

### CODE REVIEW

**Comment by martinRenou** [comment]
It seems to work only with this ugly workaround for now:
```python
import sys
import types

sys.modules['tornado'] = types.ModuleType('tornadofake')
```

Tracking this in ipympl directly: https://github.com/matplotlib/ipympl/issues/334

**Comment by jtpio** [comment]
> It seems to work only with this ugly workaround for now:

It would be totally fine to have that in the examples for now.

Or maybe we should even bake that in https://github.com/jtpio/jupyterlite/blob/main/packages/pyolite-kernel/py/pyolite/pyolite/__init__.py directly?

**Comment by martinRenou** [comment]
Yes! I can do that :)

**Comment by bollwyvl** [comment]
Not to pick on this PR (which is _raaaad_), but could we, to the extent possible, be more intentional about some of the imports hacks so that these things run under `nbconvert --execute` and `nbval`? e.g.

```py
try:
    import pyolite
    # do hacky things
except ImportError:
    pass
```

It's also worth adding a `<details><summary>Limitations</summary>...</details>` markdown cell above any cells like these to all of our examples. Totally aside, but dang i sure wish there was a good markdown flavor that supported `details`...

**Comment by martinRenou** [comment]
> be more intentional about some of the imports hacks so that these things run under nbconvert --execute and nbval?

Yeah! I guess all the `micropip.install` commands should go there as well, for all notebooks?

**Comment by jtpio** [comment]
> Yeah! I guess all the `micropip.install` commands should go there as well, for all notebooks?

Maybe, at the expense of making the code less readable?

> be more intentional about some of the imports hacks so that these things run under `nbconvert --execute` and `nbval`?

Maybe we could track this in a separate issue. For now the example notebooks are really meant to be used in JupyterLite so they could probably stay as they are?

**Comment by jtpio** [comment]
@martinRenou should we go ahead and merge this PR? I guess we can always go back to it later once https://github.com/matplotlib/matplotlib/pull/20591 is fixed

**Comment by martinRenou** [comment]
If there is no other blocker, yes :)

**Comment by jtpio** [comment]
I've added a screencast to the top comment for reference.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
