### PR TITLE
Filled-in logo icons

### PR DESCRIPTION
**Pull request by bollwyvl**
| in place | close up |
|-|-|
|  | 

## References

- one possible fix for #86

## Code changes

- adds an optional `dodo` task for updating the favicons
  - not so one-liner easy on windows, but could probably be done with `pillow`

## User-facing changes

- fills in the icon circle
- adds a currently-unused `icon-off.svg` that could be used perhaps for a loading screen

## Backwards-incompatible changes

- n/a

### CODE REVIEW

**Comment by bollwyvl** [comment]
So at present, in GHA, it reports, `doit build:favicon` reports...

```
convert-im6.q16: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1338.
convert-im6.q16: non-conforming drawing primitive definition `letter-spacing' @ error/draw.c/RenderMVGContent/4300.
convert-im6.q16: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1338.
convert-im6.q16: non-conforming drawing primitive definition `letter-spacing' @ error/draw.c/RenderMVGContent/4300.
```

...but works fine on RTD...

```
'inkscape' '/tmp/magick-158s5jV1la1Uh8U' --export-png='/tmp/magick-158D1KL9oElu2kA' --export-dpi='256,256' --export-background='rgb(0%,0%,0%)' --export-background-opacity='0' > '/tmp/magick-158gnv4ZmEQLNxf' 2>&1
mvg:/tmp/magick-158XdMBbTqE11LU=>/tmp/magick-158XdMBbTqE11LU MVG 227x227 227x227+0+0 16-bit sRGB 13.3KB 0.060u 0:00.070
/home/docs/checkouts/readthedocs.org/user_builds/jupyterlite/checkouts/92/docs/_static/icon.svg MVG 227x227 227x227+0+0 16-bit sRGB 13.3KB 0.000u 0:00.000
/home/docs/checkouts/readthedocs.org/user_builds/jupyterlite/checkouts/92/docs/_static/icon.svg=> PNG 227x227=>256x256 256x256+0+0 16-bit sRGB 1.91KB 7.8624238967895507812/0.000001/0.028717db 51.6KB 0.030u 0:00.150
/home/docs/checkouts/readthedocs.org/user_builds/jupyterlite/checkouts/92/docs/_static/icon.svg=>/home/docs/checkouts/readthedocs.org/user_builds/jupyterlite/checkouts/92/app/lab/favicon.ico MVG 227x227 227x227+0+0 16-bit sRGB 1914=>121c 7.8624238967895507812/0.000001/0.028717db 351KB 0.210u 0:00.400
```

... so I'm not too worried about this, and figure we let it slide, to be fixed in the future. Just keep calm, and check in built assets. It seems better to have something that works some of the time than nothing!

**Comment by bollwyvl** [comment]
Some alternate looks, and considering a wordmark (would be good for docs theme):

Screenshot from 2021-05-15 09-50-16

https://gist.github.com/bollwyvl/91e08e449ecfef24ab5ca87d212f61af, though it requires the Vibur font.

**Comment by jtpio** [comment]
Love it, many thanks Nick!

> and considering a wordmark (would be good for docs theme):

Those would render well in the README too!

**Comment by bollwyvl** [comment]
Some alternate looks:

Screenshot from 2021-05-15 15-09-35

**Comment by bollwyvl** [comment]
hooray quick merge for getting us to a happier compliance place. you caught me in my creative place (kinda hard with my stable, non-snap... yet non-hidpi-compatible, version of inkscape)

Whatever we end up doing here, going forward... I think getting a nice logo toolchain down will be good for folks. for example, it's probably not _necessary_ to do the full `favicon.ico` treatment, and svg would work fine.

**Pull request merged**
