### PR TITLE
DOC Deploy to gitlab pages

### PR DESCRIPTION
**Pull request by benabel**

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Since the `.gitlab-ci.yml` file is very minimal and where the GitLab specific config is, do you think it would make sense to add it to the docs too as a code snippet? (so it's easy to copy paste)

**Comment by benabel** [comment]
@jtpio I added the `.gitlab-ci.yml` snippet as you suggested.

**Review by jtpio — APPROVED** [review]
Perfect, thanks!

**Comment by benabel** [comment]
You're welcome. Thanks for your work on this open source project.

**Comment by jtpio** [comment]
btw @benabel `v0.1.0a3` has been released and includes the fix from https://github.com/jtpio/jupyterlite/pull/200

**Comment by benabel** [comment]
It seems that the error reappeared. I reopen #200.

**Pull request merged**
