### PR TITLE
Add CI job to deploy to Vercel

### PR DESCRIPTION
**Pull request by jtpio**
## References

Complement https://github.com/jtpio/jupyterlite/issues/63 and #64.

This adds an extra job to the CI workflow to upload the tarball to Vercel, and is additive to deploying the app on RTD.

Should help with documenting deployments (https://github.com/jtpio/jupyterlite/issues/67)

We may or may not want to keep that step in the future if it's unnecessary. 

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
Yeah, that's cool: the more (working) examples we have the better. Github Pages as well... though it would be worth doing a fresh `--orphan` for `gh-pages` every time... we don't need the whole history of 75mb for every tag :scream:, and people shouldn't rely on being able to pull our `gh-pages` and expect patches to work indefinitely.

**Comment by jtpio** [comment]
Looks like it worked.

**Comment by jtpio** [comment]
I think we can indeed keep this extra deployment.

And make RTD the official source of truth and update remaining links as mentioned in https://github.com/jtpio/jupyterlite/issues/63#issuecomment-826856800.

**Comment by jtpio** [comment]
Added some notes to https://github.com/jtpio/jupyterlite/issues/67#issuecomment-827091342 that we can use when adding documentation about deployments.

**Pull request merged**
