### PR TITLE
Bootstrap the `jupyterlite` command line tool

### PR DESCRIPTION
**Pull request by jtpio**
## References

Addresses some parts of #41

## Code changes

In scope for this PR:

- [x] Bootstrap the `jupyterlite` CLI tool with `flit`
- [ ] Copy existing lab extensions from `$PREFIX/share/jupyter/labextensions` to the application folder
- [ ] Update `jupyter-lite.json` with the `federated_extensions` data
- [ ] Replace some of the logic used for RTD demo to use `jupyterlite`
- [ ] Update contributing guide
- [ ] Update CI

These are the first steps to at least make it more convenient to work with third-party federated extensions locally.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
Har! I have another one of these fairly far along. There are still a few missing bits-and-bobs, and I hadn't started the docs in earnest, but it does, for example, already have the split between the labextension and the CLI, which is mostly a traitlets wrapper around our doit tasks, extracted.

Let me get a few things in order and I'll open up a PR...

**Comment by jtpio** [comment]
Sounds good, I'll pause that one for now then.

> which is mostly a traitlets wrapper around our doit tasks, extracted.

Thinking that it would be great to also be able to use the `jupyterlite` cli for development. That would mean moving some of the doit tasks to the `jupyterlite` (a bit like lab with `--dev-mode`) and have doit use `jupyterlite`.

**Comment by bollwyvl** [comment]
Yeah, #147 uses `jupyterlite` in a few places, but we might get to more. The key thing is the swappable `--app-archive`, so that you can feed it the "gold master," a development build, the docs build, whatever.

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jtpio/jupyterlite/pull/147, thanks Nick!

**Comment by bollwyvl** [comment]
No thank you, needed the kick in the pants to push!

I think we're getting close to where we would need a frank reassessment of
MVP goals... I'm thinking the service worker might need a bump.

**Comment by jtpio** [comment]
> I think we're getting close to where we would need a frank reassessment of MVP goals

We don't have a formal issue for what the MVP should look like, but the GitHub project already helps.

I'm thinking that once we have the `jupyterlite` cli tool published, folks can do there own deployments on GitHub Pages and friends with:

- content
- federated extensions
- opt-in rtc (hopefully)

`serverlite` extensions would be nice but can be added later.

**Pull request closed without merging**
