### PR TITLE
Add docs to deploy on Netlify

### PR DESCRIPTION
**Pull request by jtpio**
## References

Consolidate the documentation about deployments: #67 

I quickly tried deploying to Netlify using a similar structure as for the demo repo: https://github.com/jupyterlite/demo

And it seems to be working so far, as long as we specify 3.7 as the Python runtime.

image

## Code changes

Documentation

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
This would be very similar for Vercel except they seem to be stuck on Python 3.6 at the moment...

**Comment by bollwyvl** [comment]
We can make the CLI py-3 compatible... just a few inline type annotations not even being checked with a typechecker.

**Comment by jtpio** [comment]
Right, although if it's just for Vercel we might want to wait for them to support newer version. Looks like it it's mentioned in https://github.com/vercel/vercel/discussions/5486

**Comment by jtpio** [comment]
Since this is additive to the documentation, let's merge that and iterate if needed.

**Pull request merged**
